# CMake generated Testfile for 
# Source directory: /workspaces/CMake/Tests/CMakeTests
# Build directory: /workspaces/CMake/Tests/CMakeTests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[CMake.List]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/ListTest.cmake")
set_tests_properties([=[CMake.List]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;13;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.VariableWatch]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/VariableWatchTest.cmake")
set_tests_properties([=[CMake.VariableWatch]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;14;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.Include]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/IncludeTest.cmake")
set_tests_properties([=[CMake.Include]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;15;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.FindBase]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/FindBaseTest.cmake")
set_tests_properties([=[CMake.FindBase]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;16;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.Toolchain]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/ToolchainTest.cmake")
set_tests_properties([=[CMake.Toolchain]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;17;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.GetFilenameComponentRealpath]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/GetFilenameComponentRealpathTest.cmake")
set_tests_properties([=[CMake.GetFilenameComponentRealpath]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;18;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.Version]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/VersionTest.cmake")
set_tests_properties([=[CMake.Version]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;19;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.Message]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/MessageTest.cmake")
set_tests_properties([=[CMake.Message]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;20;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.File]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/FileTest.cmake")
set_tests_properties([=[CMake.File]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;21;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.ImplicitLinkInfo]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/ImplicitLinkInfoTest.cmake")
set_tests_properties([=[CMake.ImplicitLinkInfo]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;22;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.ModuleNotices]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/ModuleNoticesTest.cmake")
set_tests_properties([=[CMake.ModuleNotices]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;23;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.GetProperty]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/GetPropertyTest.cmake")
set_tests_properties([=[CMake.GetProperty]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;24;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.If]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/IfTest.cmake")
set_tests_properties([=[CMake.If]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;25;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.String]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/StringTest.cmake")
set_tests_properties([=[CMake.String]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;26;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.Math]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/MathTest.cmake")
set_tests_properties([=[CMake.Math]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;27;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.CMakeMinimumRequired]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/CMakeMinimumRequiredTest.cmake")
set_tests_properties([=[CMake.CMakeMinimumRequired]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;28;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.CompilerIdVendor]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/CompilerIdVendorTest.cmake")
set_tests_properties([=[CMake.CompilerIdVendor]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;29;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.ProcessorCount]=] "/workspaces/CMake/bin/cmake" "-DKWSYS_TEST_EXE=/workspaces/CMake/Source/kwsys/cmsysTestsCxx" "-P" "/workspaces/CMake/Tests/CMakeTests/ProcessorCountTest.cmake")
set_tests_properties([=[CMake.ProcessorCount]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;30;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.PushCheckState]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/PushCheckStateTest.cmake")
set_tests_properties([=[CMake.PushCheckState]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;31;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.While]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/WhileTest.cmake")
set_tests_properties([=[CMake.While]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;32;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.FileUpload]=] "/workspaces/CMake/bin/cmake" "-P" "/workspaces/CMake/Tests/CMakeTests/FileUploadTest.cmake")
set_tests_properties([=[CMake.FileUpload]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;34;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.EndStuff]=] "/workspaces/CMake/bin/cmake" "-Ddir:STRING=/workspaces/CMake/Tests/CMakeTests/EndStuffTest" "-P" "/workspaces/CMake/Tests/CMakeTests/EndStuffTest.cmake")
set_tests_properties([=[CMake.EndStuff]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;39;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.GetPrerequisites]=] "/workspaces/CMake/bin/cmake" "-DConfiguration:STRING=Release" "-P" "/workspaces/CMake/Tests/CMakeTests/GetPrerequisitesTest.cmake")
set_tests_properties([=[CMake.GetPrerequisites]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;41;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.PolicyCheck]=] "/workspaces/CMake/bin/cmake" "-DCMake_BINARY_DIR:PATH=/workspaces/CMake" "-DCMake_SOURCE_DIR:PATH=/workspaces/CMake" "-DGIT_EXECUTABLE:STRING=/usr/local/bin/git" "-P" "/workspaces/CMake/Tests/CMakeTests/PolicyCheckTest.cmake")
set_tests_properties([=[CMake.PolicyCheck]=] PROPERTIES  _BACKTRACE_TRIPLES "/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;49;AddCMakeTest;/workspaces/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
